# Generated by Django 5.2.6 on 2025-09-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0002_user_alter_job_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
